name: Continuous Integration

on:
  push:
    branches:
      - "master"
      - "staging"
      - "trying"
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["7.2", "7.3", "7.4", "8.0", "8.1"]
    name: PHP ${{ matrix.php-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Run GrumPHP
        run: vendor/bin/grumphp run
